version: '3.8'
services:    
  database:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_HOST=${DB_HOST}"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: